micronaut:
  application:
    name: mnTraining
datasources:
  default:
    url: jdbc:mysql://localhost:3306/db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    schema-generate: CREATE
    dialect: MYSQL
jpa.default.properties.hibernate.hbm2ddl.auto: update
